     

stages:
- stage: 
  jobs:
  - job: Destroy
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadBuildArtifacts@1
      displayName: 'Download Build Arifacts'
      inputs:
        buildType: specific
        project: PI-INFRA
        pipeline: Infra_Build
        downloadType: specific
        artifactName: '$(Build.BuildId)-buildid'
        extractTars: false
        
    - task: ExtractFiles@1
      displayName: Extracting files
      inputs:
        archiveFilePatterns: '$(Build.ArtifactStagingDirectory)/**/*.zip'
        destinationFolder: '$(System.DefaultWorkingDirectory)/Day8-infra-CICD/'
        overwriteExistingFiles: true
        cleanDestinationFolder: true
    
    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
      displayName: 'Terraform : Init'
      inputs:
        workingDirectory: '$(System.DefaultWorkingDirectory)/Infra-CICD-Terraform/TF-Files/'
        backendAzureRmUseEnvironmentVariablesForAuthentication: false
        backendAzureRmUseEntraIdForAuthentication: false
        backendServiceArm: 'Add_here' # replace your Azure_service_connection details in the place of Add_here
        backendAzureRmResourceGroupName: 'Add_here' # replace your Azure_resource_group details in the place of Add_here
        backendAzureRmStorageAccountName: 'Add_here' # replace your Azure_storage_account details in the place of Add_here
        backendAzureRmContainerName: 'Add_here' # replace your Azure_container details in the place of Add_here
        backendAzureRmKey: 'Add_here' # replace your Azure_backend_tfstate_file  details in the place of Add_here

    - task: ms-devlabs.custom-terraform-tasks.custom-terraform-release-task.TerraformTaskV4@4
      displayName: 'Terraform : Destroy'
      inputs:
        command: destroy
        workingDirectory: '$(System.DefaultWorkingDirectory)/Infra-CICD-Terraform/TF-Files/'
        commandOptions: '--auto-approve'
        environmentServiceNameAzureRM: 'Add_here' # replace your Azure_service_connection details in the place of Add_here
        backendAzureRmUseEnvironmentVariablesForAuthentication: false
        backendAzureRmUseEntraIdForAuthentication: false
